{application,ex_doc,
             [{registered,[]},
              {description,"ExDoc is a documentation generation tool for Elixir"},
              {applications,[kernel,stdlib,elixir,logger]},
              {vsn,"0.11.2"},
              {modules,['Elixir.ExDoc','Elixir.ExDoc.CLI',
                        'Elixir.ExDoc.Config','Elixir.ExDoc.Formatter.HTML',
                        'Elixir.ExDoc.Formatter.HTML.Autolink',
                        'Elixir.ExDoc.Formatter.HTML.Templates',
                        'Elixir.ExDoc.FunctionNode','Elixir.ExDoc.Markdown',
                        'Elixir.ExDoc.Markdown.Cmark',
                        'Elixir.ExDoc.Markdown.Earmark',
                        'Elixir.ExDoc.Markdown.Hoedown',
                        'Elixir.ExDoc.Markdown.Pandoc',
                        'Elixir.ExDoc.ModuleNode','Elixir.ExDoc.Retriever',
                        'Elixir.ExDoc.Retriever.Error',
                        'Elixir.ExDoc.TypeNode','Elixir.Mix.Tasks.Docs']}]}.